### ISSUE TITLE
Wrong repo filename for Rocky8

### ISSUE THREAD

**Issue by elcomtik** [robertdebock/ansible-role-powertools#6]
## Describe the bug

The role uses the wrong repo filename for Rocky8. The powertools_repo_file is assigned by line https://github.com/robertdebock/ansible-role-powertools/blob/master/vars/main.yml#L13, which generates filename Rocky-powertools.repo, which is not correct. The repo filename present in Rocky 8.6 image is Rocky-PowerTools.repo

This can be fixed easily by adding a new key for Rocky in _powertools_repo_file variable, if you are interested, I could make PR.

**Comment by JaegerP** [comment]
This issue also affects the Stream releases on CentOS >= 8. Instead of the generated value `CentOS-Linux-PowerTools.repo`, for these distros it should read `CentOS-Stream-PowerTools.repo`. As @elcomtik suggested, this should be possible to fix by adding an additional switch to `vars/main.yml`.

Is this role still being maintained?

**Comment by robertdebock** [comment]
Fixed with MR#7. Thanks!

**Comment by elcomtik** [comment]
LGTM, thanks a lot!
